### ISSUE TITLE
Fix crash issue

### ISSUE THREAD

**Issue by tommy5oo** [nugu-developers/nugu-android#1286]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo
{com.skt.prod.dialer/com.skt.nugu.sdk.platform.android.login.auth.NuguOAuthCallbackActivity}
: android.content.ActivityNotFoundException: No Activity found to handle Intent
{ act=android.intent.action.VIEW dat=https://... }
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8167)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
 Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent
{ act=android.intent.action.VIEW dat=https... }

at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2076)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
at android.app.Activity.startActivityForResult(Activity.java:5258)
at android.app.Activity.startActivityForResult(Activity.java:5203)
at android.app.Activity.startActivity(Activity.java:5587)
at android.app.Activity.startActivity(Activity.java:5555)
at com.skt.nugu.sdk.platform.android.login.auth.NuguOAuthCallbackActivity$c.a(NuguOAuthCallbackActivity.kt:4)
at c.a.a.a.e.a.v.c.a.a(CustomTabActivityHelper.kt:41)
at com.skt.nugu.sdk.platform.android.login.auth.NuguOAuthCallbackActivity.onCreate(NuguOAuthCallbackActivity.kt:22)
at android.app.Activity.performCreate(Activity.java:7963)
at android.app.Activity.performCreate(Activity.java:7952)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
```

**Comment by tommy5oo** [comment]
Activity found to handle Intent { act=android.intent.action.VIEW dat=https://stg-api.sktnugu.com/... (has extras) }
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://stg-api.sktnugu.com/... (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
        at android.app.Activity.startActivityForResult(Activity.java:5192)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at android.app.Activity.startActivityForResult(Activity.java:5150)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
        at android.app.Activity.startActivity(Activity.java:5521)
        at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
        at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:263)
        at com.skt.nugu.sdk.platform.android.service.webkit.NuguWebView$openInAppBrowser$1.run(NuguWebView.kt:141)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
