### ISSUE TITLE
grpc : call already half-closed

### ISSUE THREAD

**Issue by tommy5oo** [nugu-developers/nugu-android#1597]
```
java.lang.IllegalStateException: call already half-closed
  at com.google.android.material.R$style.com.google.common.base.Preconditions.checkState(Unknown Source:1)
  at io.grpc.internal.ClientCallImpl.halfCloseInternal(ClientCallImpl.java:5)  
  at io.grpc.internal.DelayedClientCall$6.run(DelayedClientCall.java:3)
  at io.grpc.internal.DelayedClientCall.drainPendingCalls(DelayedClientCall.java:13)
  at io.grpc.internal.ManagedChannelImpl$RealChannel$PendingCall$1.io.grpc.internal.DelayedClientCall.setCall(ManagedChannelImpl.java:11)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:764)
```

**Comment by shshshl09** [comment]
is this grpc-library issue?
