### ISSUE TITLE
Add feature to select thread when request android audio focus at AndroidAudioFocusInteractor

### ISSUE THREAD

**Issue by shshshl09** [nugu-developers/nugu-android#2189]

**Comment by shshshl09** [comment]
[NUGU AUTO]

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x72045db8 self=0x73ce0c84fc00
  | sysTid=6413 nice=-10 cgrp=default sched=0/0 handle=0x73ce0cddaed8
  | state=S schedstat=( 14489550226 10140640830 60340 ) utm=1169 stm=279 core=0 HZ=100
  | stack=0x7ffe53a77000-0x7ffe53a79000 stackSize=8192KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x06da6b02> (a android.media.AudioManager$SafeWaitObject)
  at java.lang.Object.wait(Object.java:442)
  at android.media.AudioManager$SafeWaitObject.safeWait(AudioManager.java:2969)
  - locked <0x06da6b02> (a android.media.AudioManager$SafeWaitObject)
  at android.media.AudioManager$BlockingFocusResultReceiver.waitForResult(AudioManager.java:3005)
  - locked <0x06da6b02> (a android.media.AudioManager$SafeWaitObject)
  at android.media.AudioManager.requestAudioFocus(AudioManager.java:2942)
  at android.media.AudioManager.requestAudioFocus(AudioManager.java:2742)
  at com.skt.nugu.sdk.platform.android.focus.AndroidAudioFocusInteractor$Impl.requestAudioFocus(AndroidAudioFocusInteractor.kt:155)
  at com.skt.nugu.sdk.platform.android.focus.AndroidAudioFocusInteractor$Impl.acquire$lambda-1(AndroidAudioFocusInteractor.kt:77)
  at com.skt.nugu.sdk.platform.android.focus.AndroidAudioFocusInteractor$Impl.lambda$ylk28PbjOb4fUuHGYOgDwEf1eO0(AndroidAudioFocusInteractor.kt:-1)
  at com.skt.nugu.sdk.platform.android.focus.-$$Lambda$AndroidAudioFocusInteractor$Impl$ylk28PbjOb4fUuHGYOgDwEf1eO0.run(lambda:-1)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
