### ISSUE TITLE
Fix crash issue

### ISSUE THREAD

**Issue by shshshl09** [nugu-developers/nugu-android#596]
2020-04-13 09:09:04.187 29410-29512/? E/AndroidRuntime: FATAL EXCEPTION: Thread-8
    Process: com.skt.nugu.sampleapp, PID: 29410
    java.lang.NullPointerException: Attempt to read from field 'int okio.Segment.limit' on a null object reference
        at okio.Buffer.write(Buffer.java:1231)
        at okio.RealBufferedSink.write(RealBufferedSink.java:40)
        at io.grpc.okhttp.internal.framed.Http2$Writer.dataFrame(Http2.java:500)
        at io.grpc.okhttp.internal.framed.Http2$Writer.data(Http2.java:493)
        at io.grpc.okhttp.ExceptionHandlingFrameWriter.data(ExceptionHandlingFrameWriter.java:162)
        at io.grpc.okhttp.OutboundFlowController$OutboundFlowState.write(OutboundFlowController.java:326)
        at io.grpc.okhttp.OutboundFlowController.data(OutboundFlowController.java:125)
        at io.grpc.okhttp.OkHttpClientStream$TransportState.sendBuffer(OkHttpClientStream.java:378)
        at io.grpc.okhttp.OkHttpClientStream$TransportState.access$700(OkHttpClientStream.java:189)
        at io.grpc.okhttp.OkHttpClientStream$Sink.writeFrame(OkHttpClientStream.java:169)
        at io.grpc.internal.AbstractClientStream.deliverFrame(AbstractClientStream.java:196)
        at io.grpc.internal.MessageFramer.commitToSink(MessageFramer.java:350)
        at io.grpc.internal.MessageFramer.flush(MessageFramer.java:300)
        at io.grpc.internal.AbstractStream.flush(AbstractStream.java:63)
        at io.grpc.internal.ForwardingClientStream.flush(ForwardingClientStream.java:42)
        at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:476)
        at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:447)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:341)
        at com.skt.nugu.sdk.client.port.transport.grpc.devicegateway.EventStreamService.sendEventMessage(EventStreamService.kt:157)
        at com.skt.nugu.sdk.client.port.transport.grpc.devicegateway.DeviceGatewayClient.send(DeviceGatewayClient.kt:154)
        at com.skt.nugu.sdk.client.port.transport.grpc.GrpcTransport.send(GrpcTransport.kt:231)
        at com.skt.nugu.sdk.core.network.MessageRouter.sendMessage(MessageRouter.kt:120)
        at com.skt.nugu.sdk.core.network.NetworkManager.sendMessage(Unknown Source:7)
        at com.skt.nugu.sdk.agent.DefaultTTSAgent$sendEventWithToken$1.onContextAvailable(DefaultTTSAgent.kt:814)
        at com.skt.nugu.sdk.core.context.ContextManager.sendContextAndClearQueue(ContextManager.kt:164)
        at com.skt.nugu.sdk.core.context.ContextManager.sendContextToRequesters(ContextManager.kt:124)
        at com.skt.nugu.sdk.core.context.ContextManager.access$sendContextToRequesters(ContextManager.kt:34)
        at com.skt.nugu.sdk.core.context.ContextManager$updateStatesThread$1.onLoop(ContextManager.kt:61)
        at com.skt.nugu.sdk.core.utils.LoopThread.run(LoopThread.kt:29)

**Comment by shshshl09** [comment]
refer to: https://github.com/square/okio/issues/683
(concurrent issue)
