### ISSUE TITLE
GsonUtils.deepMerge crash

### ISSUE THREAD

**Issue by tommy5oo** [nugu-developers/nugu-android#847]
```
java.lang.IllegalStateException: Not a JSON Object: "오늘 뉴스 알려줘" 
 at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) 
 at com.skt.nugu.sdk.agent.util.GsonUtilsKt.deepMerge(GsonUtils.kt:34) 
 at com.skt.prod.dialer.nugu.audio.AudioPlayerRenderer.update(AudioPlayerRenderer.kt:220)
```

**Comment by shshshl09** [comment]
The first version seems to work fine.
What is the problem of the first version?

```kotlin
@Throws(Exception::class)
fun JsonObject.deepMerge(source: JsonObject) {
    for ((key, value) in source.entrySet()) {
        if (!has(key)) { //target does not have the same key, so perhaps it should be added to target
            if (!value.isJsonNull) //well, only add if the source value is not null
                add(key, value)
        } else {
            if (!value.isJsonNull) {
                if (value.isJsonObject) { //source value is json object, start deep merge
                    get(key).asJsonObject.deepMerge(value.asJsonObject)
                } else {
                    add(key, value)
                }
            } else {
                remove(key)
            }
        }
    }
}
